### PR TITLE
Fixed file name

### PR DESCRIPTION
**Pull request by DoppioNattapon**

### CODE REVIEW

**Review by massarinb — CHANGES_REQUESTED** [review]
filename is not correct as assignment ka.
it's to be this pattern <yourname>_first_robot.robot

**Review by ItsTiss — APPROVED** [review]
Approved kub

**Review by wisalyatb — APPROVED** [review]
Approved

**Review by massarinb — APPROVED** [review]
approved

**Review by ppimwalun — APPROVED** [review]
Approved ka

**Review by Jidapa-Mint — APPROVED** [review]
Checked and Approved

**Pull request merged**
